apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-blog-green
spec:
  replicas: 1
  selector:
    matchLabels:
      app: post-blog
      version: green
  template:
    metadata:
      labels:
        app: post-blog
        version: green
    spec:
      containers:
      - name: post-blog
        image: aravindh05/post-blog
        ports:
        - containerPort: 5000
        env:
        - name: mongo_uri
          value: "mongodb://mongo-service:27017/blogdb"

