apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blue-app
      version: blue
  template:
    metadata:
      labels:
        app: blue-app
        version: blue
    spec:
      containers:
      - name: blue-container
        image: aravindh05/blue-deployment:latest
        ports:
        - containerPort: 5000
        env:
        - name: MONGODB_URL
          value: "mongodb://mongo-service:27017/blogdb"
        

