# mongo-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-green-deployment
  labels:
    app: mongo-green
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-green
  template:
    metadata:
      labels:
        app: mongo-green
    spec:
      containers:
      - name: mongo
        image: mongo  # You can specify the version you need
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongo-storage
          mountPath: /data/db
      volumes:
      - name: mongo-storage
        persistentVolumeClaim:
          claimName: mongo-green-pvc

---

# mongo-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  selector:
    app: mongo-green
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  type: ClusterIP


