# mongo-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-green-deployment
  labels:
    app: mongo-greens
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-greens
  template:
    metadata:
      labels:
        app: mongo-greens
    spec:
      containers:
      - name: mongo
        image: mongo:latest  # You can specify the version you need
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongo-storages
          mountPath: /data/db
      volumes:
      - name: mongo-storages
        persistentVolumeClaim:
          claimName: mongo-green-pvc

---

# mongo-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  selector:
    app: mongo-greens
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  type: ClusterIP
