apiVersion: v1
kind: Service
metadata:
  name: service-deploy
spec:
  selector:
    app: blue-app
    version: blue
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
