apiVersion: v1
kind: Service
metadata:
  name: post-blog-service
spec:
  selector:
    app: post-blog
    version: blue
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer