apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-greens
spec:
  capacity:
    storage: 10Gi  # Adjust the size as needed
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data/mongo  # Path to store data on the host

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-green-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
 
